name: Arch Image Builder

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mkosi
        run: |
          git clone --depth 1 https://github.com/systemd/mkosi
          sudo ln -s $PWD/mkosi/bin/mkosi /usr/local/bin/mkosi
          mkosi --version

      - uses: ./mkosi

      - name: Configure
        working-directory: mkosi
        run: |
          tee mkosi.local.conf <<EOF
          [Distribution]
          Distribution=arch
          
          [Output]
          ManifestFormat=json
          
          [Content]
          KernelCommandLine=systemd.default_device_timeout_sec=180
          Packages=base,pacman
          
          [Build]
          ToolsTreeDistribution=arch
          Environment=SYSTEMD_REPART_MKFS_OPTIONS_EROFS="--quiet"
          
          [Runtime]
          KVM=yes
          EOF

      - name: Create skeleton directory
        working-directory: mkosi
        run: mkdir -p mkosi.skeleton/etc/pacman.d/hooks

      - name: Generate key
        working-directory: mkosi
        run: sudo mkosi genkey

      - name: Summary
        working-directory: mkosi
        run: sudo mkosi summary

      - name: Build tools tree
        working-directory: mkosi
        run: sudo mkosi -f box -- true

      - name: Build image
        working-directory: mkosi
        run: sudo mkosi -f

      - name: Build Arch Linux image
        working-directory: mkosi
        run: |
          sudo mkosi --distribution=arch \
            --format=directory \
            build
