name: Arch Image Builder

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mkosi
        run: |
          git clone https://github.com/systemd/mkosi
          sudo ln -s $PWD/mkosi/bin/mkosi /usr/local/bin/mkosi
          mkosi --version
      
      - name: Generate key
        run: sudo mkosi genkey

      - name: Summary
        run: sudo mkosi summary

      - name: Build tools tree
        run: sudo mkosi -f box -- true

      - name: Build image
        run: sudo mkosi -f

      - name: Build Arch Linux image
        run: |
          sudo mkosi --distribution=arch \
            --format=directory \
            build
